version: "3.8"
services:
  userdb:
    image: mongo
    container_name: userdb
    env_file: ./.env
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=mongodb
      #- MONGO_INITDB_ROOT_PASSWORD=mongodb
      #- MONGO_INITDB_DATABASE=userapi
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DATABASE
    volumes:
      - ./Mongodb:/data/db
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    restart: unless-stopped

  userapi:
    container_name: userapi
    depends_on:
      - userdb
    build: ./userproject
    restart: unless-stopped
    env_file: ./.env
    command: python manage.py runserver
    ports:
      - $USERAPI_LOCAL_PORT:$USERAPI_DOCKER_PORT
    environment:
      - DB_USER=$MONGO_USER
      - DB_PASSWORD=$MONGO_PASSWORD
      - DB_NAME=$MONGO_DATABASE
      - DB_PORT=$MONGO_DOCKER_PORT
      - DB_HOST=$USERAPI_DBHOST
    #stdin_open: true
    #tty: true
    volumes:
      - ./userproject:/userapp
    links:
      - userdb:userdb

  productdb:
    image: mysql:5.7
    container_name: productdb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes: 
      - ./Mysql:/var/lib/mysql
  productapi:
    container_name: productapi
    depends_on:
      - productdb
    build: ./productproject
    restart: unless-stopped
    env_file: ./.env
    command: python manage.py runserver
    ports:
      - $PRODUCTAPI_LOCAL_PORT:$PRODUCTAPI_DOCKER_PORT
    environment:
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - DB_HOST=$PRODUCTAPI_DBHOST
    #stdin_open: true
    #tty: true
    volumes:
      - ./productproject:/productapp
    links:
      - productdb:productdb
volumes:
  Mongodb:
  Mysql: