# Generated by Django 3.2.9 on 2021-11-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=70)),
                ('senha', models.CharField(default='', max_length=12)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
