# Generated by Django 3.2.9 on 2021-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=20)),
                ('descricao', models.CharField(default='', max_length=70)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0)),
            ],
        ),
    ]
